services:
  minecraft:
    image: itzg/minecraft-server:stable
    restart: always
    container_name: Vanilla
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      LEVEL_NAME: Vanilla
      SERVER_NAME: Vanilla
      VERSION: 1.20.4
      ONLINE_MODE: FALSE
    volumes:
      - /home/user/Downloads/minecraft_packs/vanilla:/data/world
    user: "1000:1000"
networks:
  minecraft_net:
    external: true
